// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: consuming/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGoldPriceRequest struct {
	RequestId int64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *QueryGoldPriceRequest) Reset()         { *m = QueryGoldPriceRequest{} }
func (m *QueryGoldPriceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGoldPriceRequest) ProtoMessage()    {}
func (*QueryGoldPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38b0adbddb76ede3, []int{0}
}
func (m *QueryGoldPriceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGoldPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGoldPriceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGoldPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGoldPriceRequest.Merge(m, src)
}
func (m *QueryGoldPriceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGoldPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGoldPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGoldPriceRequest proto.InternalMessageInfo

func (m *QueryGoldPriceRequest) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

type QueryGoldPriceResponse struct {
	Result *GoldPriceResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *QueryGoldPriceResponse) Reset()         { *m = QueryGoldPriceResponse{} }
func (m *QueryGoldPriceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGoldPriceResponse) ProtoMessage()    {}
func (*QueryGoldPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38b0adbddb76ede3, []int{1}
}
func (m *QueryGoldPriceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGoldPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGoldPriceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGoldPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGoldPriceResponse.Merge(m, src)
}
func (m *QueryGoldPriceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGoldPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGoldPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGoldPriceResponse proto.InternalMessageInfo

func (m *QueryGoldPriceResponse) GetResult() *GoldPriceResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type QueryLastGoldPriceIdRequest struct {
}

func (m *QueryLastGoldPriceIdRequest) Reset()         { *m = QueryLastGoldPriceIdRequest{} }
func (m *QueryLastGoldPriceIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLastGoldPriceIdRequest) ProtoMessage()    {}
func (*QueryLastGoldPriceIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38b0adbddb76ede3, []int{2}
}
func (m *QueryLastGoldPriceIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLastGoldPriceIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLastGoldPriceIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLastGoldPriceIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLastGoldPriceIdRequest.Merge(m, src)
}
func (m *QueryLastGoldPriceIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLastGoldPriceIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLastGoldPriceIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLastGoldPriceIdRequest proto.InternalMessageInfo

type QueryLastGoldPriceIdResponse struct {
	RequestId int64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *QueryLastGoldPriceIdResponse) Reset()         { *m = QueryLastGoldPriceIdResponse{} }
func (m *QueryLastGoldPriceIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLastGoldPriceIdResponse) ProtoMessage()    {}
func (*QueryLastGoldPriceIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38b0adbddb76ede3, []int{3}
}
func (m *QueryLastGoldPriceIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLastGoldPriceIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLastGoldPriceIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLastGoldPriceIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLastGoldPriceIdResponse.Merge(m, src)
}
func (m *QueryLastGoldPriceIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLastGoldPriceIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLastGoldPriceIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLastGoldPriceIdResponse proto.InternalMessageInfo

func (m *QueryLastGoldPriceIdResponse) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryGoldPriceRequest)(nil), "cosmonaut.interchange.consuming.QueryGoldPriceRequest")
	proto.RegisterType((*QueryGoldPriceResponse)(nil), "cosmonaut.interchange.consuming.QueryGoldPriceResponse")
	proto.RegisterType((*QueryLastGoldPriceIdRequest)(nil), "cosmonaut.interchange.consuming.QueryLastGoldPriceIdRequest")
	proto.RegisterType((*QueryLastGoldPriceIdResponse)(nil), "cosmonaut.interchange.consuming.QueryLastGoldPriceIdResponse")
}

func init() { proto.RegisterFile("consuming/query.proto", fileDescriptor_38b0adbddb76ede3) }

var fileDescriptor_38b0adbddb76ede3 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x3f, 0x4b, 0xf3, 0x40,
	0x1c, 0xc7, 0x9b, 0xa7, 0x3c, 0x05, 0xcf, 0x41, 0x38, 0xa8, 0x48, 0x6c, 0xa3, 0x64, 0xf2, 0x0f,
	0xe4, 0x6c, 0xc5, 0x76, 0xb1, 0x8b, 0x8b, 0x16, 0x3a, 0x68, 0x47, 0x97, 0x70, 0x49, 0x8e, 0xf4,
	0x20, 0xbd, 0x4b, 0x73, 0x17, 0xb1, 0x88, 0x8b, 0x6f, 0x40, 0xc1, 0x57, 0xe4, 0xe6, 0x58, 0x70,
	0x71, 0x94, 0xd6, 0x17, 0x22, 0xbd, 0x84, 0x36, 0x96, 0x68, 0xd5, 0x2d, 0xdc, 0xfd, 0x3e, 0xbf,
	0x7c, 0x3f, 0xdf, 0x04, 0x94, 0x5d, 0xce, 0x44, 0xdc, 0xa7, 0xcc, 0x47, 0x83, 0x98, 0x44, 0x43,
	0x2b, 0x8c, 0xb8, 0xe4, 0x70, 0xcb, 0xe5, 0xa2, 0xcf, 0x19, 0x8e, 0xa5, 0x45, 0x99, 0x24, 0x91,
	0xdb, 0xc3, 0xcc, 0x27, 0xd6, 0x6c, 0x58, 0xaf, 0xf8, 0x9c, 0xfb, 0x01, 0x41, 0x38, 0xa4, 0x08,
	0x33, 0xc6, 0x25, 0x96, 0x94, 0x33, 0x91, 0xe0, 0xfa, 0x9e, 0xc2, 0x05, 0x72, 0xb0, 0x20, 0xc9,
	0x5e, 0x74, 0x55, 0x73, 0x88, 0xc4, 0x35, 0x14, 0x62, 0x9f, 0x32, 0x35, 0x9c, 0xce, 0xea, 0xf3,
	0x04, 0x3e, 0x0f, 0x3c, 0x3b, 0x8c, 0xa8, 0x4b, 0x92, 0x3b, 0xb3, 0x01, 0xca, 0x17, 0x53, 0xfa,
	0x94, 0x07, 0xde, 0xf9, 0xf4, 0xbc, 0x4b, 0x06, 0x31, 0x11, 0x12, 0x56, 0x01, 0x88, 0x92, 0x47,
	0x9b, 0x7a, 0x1b, 0xda, 0xb6, 0xb6, 0x53, 0xec, 0xae, 0xa4, 0x27, 0x6d, 0xcf, 0x74, 0xc0, 0xfa,
	0x22, 0x27, 0x42, 0xce, 0x04, 0x81, 0x67, 0xa0, 0x14, 0x11, 0x11, 0x07, 0x52, 0x41, 0xab, 0xf5,
	0x03, 0x6b, 0x89, 0xa9, 0x95, 0xdd, 0x11, 0x07, 0xb2, 0x9b, 0xf2, 0x66, 0x15, 0x6c, 0xaa, 0x77,
	0x74, 0xb0, 0x90, 0xb3, 0x99, 0xb6, 0x97, 0x26, 0x34, 0x5b, 0xa0, 0x92, 0x7f, 0x9d, 0x06, 0xf9,
	0xde, 0xa0, 0x7e, 0x5f, 0x04, 0xff, 0x15, 0x0f, 0x9f, 0x34, 0xb0, 0xb6, 0x90, 0x01, 0x36, 0x96,
	0xa6, 0xce, 0xad, 0x4d, 0x6f, 0xfe, 0x9a, 0x4b, 0xd2, 0x9a, 0xad, 0xbb, 0x97, 0xf7, 0xc7, 0x7f,
	0x4d, 0x78, 0x84, 0x32, 0x18, 0xca, 0xfb, 0x72, 0x76, 0x52, 0x0f, 0xba, 0x99, 0xdb, 0xdd, 0x2a,
	0x87, 0x85, 0x22, 0xe0, 0xf1, 0xcf, 0xb2, 0xe4, 0xd7, 0xab, 0xb7, 0xfe, 0x48, 0xa7, 0x3e, 0x35,
	0xe5, 0xb3, 0x0f, 0x77, 0xbf, 0xf0, 0x09, 0xb0, 0x90, 0x76, 0x46, 0x8a, 0x7a, 0x27, 0x9d, 0xe7,
	0xb1, 0xa1, 0x8d, 0xc6, 0x86, 0xf6, 0x36, 0x36, 0xb4, 0x87, 0x89, 0x51, 0x18, 0x4d, 0x8c, 0xc2,
	0xeb, 0xc4, 0x28, 0x5c, 0xd6, 0x7d, 0x2a, 0x7b, 0xb1, 0x63, 0xb9, 0xbc, 0x8f, 0x66, 0xa9, 0x3e,
	0x2d, 0xbe, 0xce, 0xac, 0x96, 0xc3, 0x90, 0x08, 0xa7, 0xa4, 0x7e, 0xf0, 0xc3, 0x8f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x2e, 0x8f, 0xd4, 0x1a, 0x80, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// GoldPriceResult defines a rpc handler method for MsgGoldPriceData.
	GoldPriceResult(ctx context.Context, in *QueryGoldPriceRequest, opts ...grpc.CallOption) (*QueryGoldPriceResponse, error)
	// LastGoldPriceId query the last GoldPrice result id
	LastGoldPriceId(ctx context.Context, in *QueryLastGoldPriceIdRequest, opts ...grpc.CallOption) (*QueryLastGoldPriceIdResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GoldPriceResult(ctx context.Context, in *QueryGoldPriceRequest, opts ...grpc.CallOption) (*QueryGoldPriceResponse, error) {
	out := new(QueryGoldPriceResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.interchange.consuming.Query/GoldPriceResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LastGoldPriceId(ctx context.Context, in *QueryLastGoldPriceIdRequest, opts ...grpc.CallOption) (*QueryLastGoldPriceIdResponse, error) {
	out := new(QueryLastGoldPriceIdResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.interchange.consuming.Query/LastGoldPriceId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// GoldPriceResult defines a rpc handler method for MsgGoldPriceData.
	GoldPriceResult(context.Context, *QueryGoldPriceRequest) (*QueryGoldPriceResponse, error)
	// LastGoldPriceId query the last GoldPrice result id
	LastGoldPriceId(context.Context, *QueryLastGoldPriceIdRequest) (*QueryLastGoldPriceIdResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GoldPriceResult(ctx context.Context, req *QueryGoldPriceRequest) (*QueryGoldPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoldPriceResult not implemented")
}
func (*UnimplementedQueryServer) LastGoldPriceId(ctx context.Context, req *QueryLastGoldPriceIdRequest) (*QueryLastGoldPriceIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastGoldPriceId not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GoldPriceResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGoldPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GoldPriceResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.interchange.consuming.Query/GoldPriceResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GoldPriceResult(ctx, req.(*QueryGoldPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LastGoldPriceId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLastGoldPriceIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LastGoldPriceId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.interchange.consuming.Query/LastGoldPriceId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LastGoldPriceId(ctx, req.(*QueryLastGoldPriceIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmonaut.interchange.consuming.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GoldPriceResult",
			Handler:    _Query_GoldPriceResult_Handler,
		},
		{
			MethodName: "LastGoldPriceId",
			Handler:    _Query_LastGoldPriceId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consuming/query.proto",
}

func (m *QueryGoldPriceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGoldPriceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGoldPriceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGoldPriceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGoldPriceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGoldPriceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Result != nil {
		{
			size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLastGoldPriceIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLastGoldPriceIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLastGoldPriceIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryLastGoldPriceIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLastGoldPriceIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLastGoldPriceIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGoldPriceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovQuery(uint64(m.RequestId))
	}
	return n
}

func (m *QueryGoldPriceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Result != nil {
		l = m.Result.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLastGoldPriceIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryLastGoldPriceIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovQuery(uint64(m.RequestId))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGoldPriceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGoldPriceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGoldPriceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGoldPriceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGoldPriceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGoldPriceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Result == nil {
				m.Result = &GoldPriceResult{}
			}
			if err := m.Result.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLastGoldPriceIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLastGoldPriceIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLastGoldPriceIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLastGoldPriceIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLastGoldPriceIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLastGoldPriceIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
